publish = false

pre-release-replacements = [
  {file="CRATE_README.md", search="inquire = \".*\"", replace="inquire = \"{{version}}\""},
  {file="CRATE_README.md", search="inquire = \\{ version = \"[\\.0-9]*\"", replace="inquire = { version = \"{{version}}\""},
  {file="CRATE_README.md", search="inquire-derive = \".*\"", replace="inquire-derive = \"{{version}}\""},
  {file="CRATE_README.md", search="inquire-derive = \\{ version = \"[\\.0-9]*\"", replace="inquire-derive = { version = \"{{version}}\""},
]
