name: CHANGELOG Check

on:
  - pull_request
  - issue_comment

jobs:
  check:
    if: (${{ github.event.issue.pull_request }} || ${{ github.event_name == 'pull_request' }})
    runs-on: ubuntu-latest

    steps:
      - name: Check if CHANGELOG is not required
        run: |
          PR_COMMENTS=$( \
            curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          )

          readarray -t comments < <(jq -c '.[]' <<<"$PR_COMMENTS")
          IFS=$'\n' #read til newline
          CHECK_CHANGELOG=true

          for item in "${comments[@]}"; do
            author_association=$(jq --raw-output '.author_association' <<< "$item")
            body=$(jq --raw-output '.body' <<< "$item")
            
            if [[ "$author_association" == "OWNER" || "$author_association" == "COLLABORATOR" ]]; then
              # if body is no-changelog, set var to false, else if body is require-changelog, set var to true.
              if [[ "$body" == "/no-changelog" ]]; then
                CHECK_CHANGELOG=false
              elif [[ "$body" == "/require-changelog" ]]; then
                CHECK_CHANGELOG=true
              fi
            fi
          done

          echo $COMMENTS

          echo $CHECK_CHANGELOG

          echo "CHECK_CHANGELOG=$CHECK_CHANGELOG" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
