name: CHANGELOG Check

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch PR Comments
        id: fetch_comments
        run: |
          PR_COMMENTS=$( \
            echo $( \
              curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            ) \
            | jq -c '.[].body' \
            | base64 \
          )
          echo "PR_COMMENTS=$PR_COMMENTS" >> $GITHUB_ENV

      - name: Check if CHANGELOG is not required
        run: |
          if echo "${{ env.COMMENTS }}" | grep -q "/ignore-workflow"; then
            echo "Ignore workflow comment found, skipping all actions"
            exit 78
          fi
        if: |
          contains(env.COMMENTS, '/ignore-workflow') &&
          github.event.sender.permissions.push == true

      - name: Checkout code
        uses: actions/checkout@v2
