name: Open a release PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

env:
  CRATE_NAME: inquire

jobs:
  make-release-pr:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release

      - uses: cargo-bins/release-pr@v2
        with:
          check-semver: true
          pr-release-notes: true
          base-branch: main
          crate-name: ${{ env.CRATE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
